# File version
version: '3'

# Service (Container) configurations
services:

  # Nginx service
  nginx:
    # Container name to be created
    container_name: nginx

    # Path to the Dockerfile
    build: ./requirements/nginx

    # Ports to be mapped for incoming connections
    ports:
      - 443:443
    
    # Volume for storing files
    volumes:
      - wordpress_data:/var/www/html

    # Automatically restart the container
    restart: always

    # Network the container is connected to
    networks:
      - network

  # MariaDB service
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb

    # Volume for persisting MariaDB data
    volumes:
      - mariadb_data:/var/lib/mysql

    # Network the container is connected to
    networks:
      - network

    # Load environment variables from .env file
    env_file:
      - .env

    # Automatically restart the container
    restart: always

  # WordPress service
  wordpress:
    container_name: wordpress

    # Depends on the MariaDB service
    depends_on:
      - mariadb

    # Build context and Dockerfile path for WordPress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile

    # Automatically restart the container
    restart: always

    # Load environment variables from .env file
    env_file:
      - .env

    # Volume for storing WordPress files
    volumes:
      - wordpress_data:/var/www/html

    # Network the container is connected to
    networks:
      - network

# Volumes to store data for services and connect to the host system
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/data/wordpress
      o: bind

# Default network connected to the bridge driver
networks:
  network:
    driver: bridge
